const { createClient } = require('@supabase/supabase-js');
const crypto = require('crypto');
const db = createClient(process.env.SUPABASE_URL, process.env.SUPABASE_SERVICE_ROLE_KEY);
const out=(status,body)=>({statusCode:status,headers:{'Content-Type':'application/json','Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'Content-Type,Authorization','Access-Control-Allow-Methods':'GET,POST,OPTIONS'},body:JSON.stringify(body)});
const hash=s=>crypto.createHash('sha256').update(s).digest('hex');
async function uid(event){const t=(event.headers.authorization||'').replace('Bearer ','');if(!t)return null;const {data}=await db.from('sessions').select('user_id,expires_at').eq('token',t).single();return data&&new Date(data.expires_at)>new Date()?data.user_id:null}
exports.handler=async e=>{if(e.httpMethod==='OPTIONS')return out(204,{});try{const path=e.path.replace(/^.*?functions\/api/,'')||'/';const b=e.body?JSON.parse(e.body):{};
if(path==='/auth/signup'&&e.httpMethod==='POST'){if(!b.email||!b.password)return out(400,{error:'Email and password required'});const {data:u,error}=await db.from('users').insert({email:b.email,password_hash:hash(b.password)}).select('id,email').single();if(error)return out(400,{error:'Email may already be registered'});const token=crypto.randomBytes(32).toString('hex');await db.from('sessions').insert({token,user_id:u.id,expires_at:new Date(Date.now()+30*864e5).toISOString()});return out(200,{token,user:u})}
if(path==='/auth/login'&&e.httpMethod==='POST'){const {data:u}=await db.from('users').select('id,email').eq('email',b.email).eq('password_hash',hash(b.password)).single();if(!u)return out(401,{error:'Invalid email or password'});const token=crypto.randomBytes(32).toString('hex');await db.from('sessions').insert({token,user_id:u.id,expires_at:new Date(Date.now()+30*864e5).toISOString()});return out(200,{token,user:u})}
const user=await uid(e);if(!user)return out(401,{error:'Please log in'});
if(path==='/me')return out(200,{user_id:user});
if(path==='/data'){const {data:accounts}=await db.from('accounts').select('*').eq('user_id',user).order('created_at');const ids=(accounts||[]).map(a=>a.id);const {data:trades}=ids.length?await db.from('trades').select('*').in('account_id',ids).order('created_at'):{data:[]};return out(200,{accounts:accounts||[],trades:trades||[]})}
if(path==='/accounts'&&e.httpMethod==='POST'){const {data,error}=await db.from('accounts').insert({...b,user_id:user}).select().single();if(error)return out(400,{error:error.message});return out(200,{account:data})}
if(path==='/trades'&&e.httpMethod==='POST'){const {data:a}=await db.from('accounts').select('*').eq('id',b.account_id).eq('user_id',user).single();if(!a)return out(404,{error:'Account not found'});const {data:old}=await db.from('trades').select('pnl').eq('account_id',a.id);const bal=a.account_size+(old||[]).reduce((s,t)=>s+Number(t.pnl),0)+Number(b.pnl||0);const {data,error}=await db.from('trades').insert({...b,balance_after:bal}).select().single();if(error)return out(400,{error:error.message});return out(200,{trade:data})}
return out(404,{error:'Not found'})}catch(err){return out(500,{error:err.message})}};
