let account={firm:"Demo Prop Firm",name:"$100K Account",accountSize:100000,targetType:"percent",targetInput:8,maxDDType:"percent",maxDDInput:10,dailyDDType:"percent",dailyDDInput:5,trades:[]};let ruleTypes={target:"usd",maxDD:"usd",dailyDD:"usd"};
const money=v=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:2}).format(v||0);
function calculateValue(type){let size=+document.getElementById("accountSize").value||0,input=+document.getElementById(type+"Value").value||0;return ruleTypes[type]==="percent"?size*input/100:input}
function calculateRules(){document.getElementById("targetCalculated").textContent=money(calculateValue("target"));document.getElementById("maxDDCalculated").textContent=money(calculateValue("maxDD"));document.getElementById("dailyDDCalculated").textContent=money(calculateValue("dailyDD"))}
function setRuleType(type,mode){ruleTypes[type]=mode;document.getElementById(type+"UsdBtn").classList.toggle("selected",mode==="usd");document.getElementById(type+"PercentBtn").classList.toggle("selected",mode==="percent");calculateRules()}
function openAccountModal(){document.getElementById("accountModal").classList.remove("hidden");calculateRules()}
function closeAccountModal(){document.getElementById("accountModal").classList.add("hidden")}
function saveAccount(){account.firm=document.getElementById("firm").value||"My Prop Firm";account.name=document.getElementById("accountName").value||"Trading Account";account.accountSize=+document.getElementById("accountSize").value||0;account.targetType=ruleTypes.target;account.targetInput=+document.getElementById("targetValue").value||0;account.maxDDType=ruleTypes.maxDD;account.maxDDInput=+document.getElementById("maxDDValue").value||0;account.dailyDDType=ruleTypes.dailyDD;account.dailyDDInput=+document.getElementById("dailyDDValue").value||0;saveData();closeAccountModal();updateDashboard()}
function targetValue(){return account.targetType==="percent"?account.accountSize*account.targetInput/100:account.targetInput}
function maxDDValue(){return account.maxDDType==="percent"?account.accountSize*account.maxDDInput/100:account.maxDDInput}
function dailyDDValue(){return account.dailyDDType==="percent"?account.accountSize*account.dailyDDInput/100:account.dailyDDInput}
function currentBalance(){return account.accountSize+account.trades.reduce((s,t)=>s+t.pnl,0)}
function todayPnL(){let d=new Date().toISOString().slice(0,10);return account.trades.filter(t=>t.date.startsWith(d)).reduce((s,t)=>s+t.pnl,0)}
function updateDashboard(){let balance=currentBalance(),target=targetValue(),max=maxDDValue(),daily=dailyDDValue(),profit=balance-account.accountSize,maxUsed=Math.max(0,-profit),todayLoss=Math.max(0,-todayPnL()),targetProgress=Math.max(0,Math.min(100,profit/target*100));document.getElementById("balance").textContent=money(balance);document.getElementById("target").textContent=money(target);document.getElementById("targetRemaining").textContent=money(Math.max(0,target-profit))+" remaining";document.getElementById("maxDD").textContent=money(Math.max(0,max-maxUsed));document.getElementById("dailyDD").textContent=money(Math.max(0,daily-todayLoss));document.getElementById("targetPercent").textContent=targetProgress.toFixed(1)+"%";document.getElementById("targetBar").style.width=targetProgress+"%";document.getElementById("maxDDPercent").textContent=((maxUsed/max)*100).toFixed(1)+"%";document.getElementById("maxDDBar").style.width=Math.min(100,maxUsed/max*100)+"%";document.getElementById("dailyDDPercent").textContent=((todayLoss/daily)*100).toFixed(1)+"%";document.getElementById("dailyDDBar").style.width=Math.min(100,todayLoss/daily*100)+"%";updateTradePreview();renderHistory();renderAccount()}
function saveTrade(e){e.preventDefault();let pnl=+document.getElementById("tradePnL").value;account.trades.push({date:new Date().toISOString(),pair:document.getElementById("pair").value.toUpperCase(),direction:document.getElementById("direction").value,pnl,entry:document.getElementById("entry").value,exit:document.getElementById("exit").value,lot:document.getElementById("lot").value,notes:document.getElementById("tradeNotes").value});saveData();document.getElementById("tradeForm").reset();updateDashboard();showPage("dashboard")}
function updateTradePreview(){let pnl=+document.getElementById("tradePnL")?.value||0,b=currentBalance()+pnl,profit=b-account.accountSize;document.getElementById("tradeBalance").textContent=money(b);document.getElementById("tradeMaxDD").textContent=money(Math.max(0,maxDDValue()-Math.max(0,-profit)));document.getElementById("tradeDailyDD").textContent=money(Math.max(0,dailyDDValue()-Math.max(0,-(todayPnL()+pnl))))}
function renderHistory(){let body=document.getElementById("tradeHistory");body.innerHTML="";account.trades.slice().reverse().forEach(t=>{let r=document.createElement("tr");let idx=account.trades.indexOf(t);let bal=account.accountSize+account.trades.slice(0,idx+1).reduce((s,x)=>s+x.pnl,0);r.innerHTML=`<td>${new Date(t.date).toLocaleString()}</td><td>${t.pair}</td><td>${t.direction}</td><td>${money(t.pnl)}</td><td>${money(bal)}</td>`;body.appendChild(r)})}
function renderAccount(){let el=document.getElementById("accountList");if(!el)return;el.innerHTML=`<div class="card"><small>${account.firm}</small><h3>${account.name}</h3><p>Size: ${money(account.accountSize)}</p><p>Target: ${money(targetValue())} · Max DD: ${money(maxDDValue())} · Daily DD: ${money(dailyDDValue())}</p></div>`}
function showPage(page){document.querySelectorAll(".page").forEach(p=>p.classList.add("hidden"));document.getElementById(page).classList.remove("hidden");document.getElementById("pageTitle").textContent=page==="trade"?"New Trade":page.charAt(0).toUpperCase()+page.slice(1);updateDashboard()}
function saveData(){localStorage.setItem("proptrack_account",JSON.stringify(account))}
function loadData(){let s=localStorage.getItem("proptrack_account");if(s)account=JSON.parse(s)}
document.getElementById("tradeForm").addEventListener("submit",saveTrade);document.getElementById("tradePnL").addEventListener("input",updateTradePreview);loadData();updateDashboard();